name: Static Analysis with Semgrep (SAST)

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  sast:
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Semgrep scan
        run: semgrep --config=p/security-audit authenticate-example-master --json > sast_results.json

      - name: Store scan results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: sast-results
          path: sast_results.json