name: Static Analysis with Semgrep (SAST)

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  sast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Semgrep
        run: |
          wget -q -O semgrep.sh https://semgrep.dev/install.sh
          sudo bash semgrep.sh

      - name: Run Semgrep scan
        run: semgrep --config=p/security-audit . --json > sast_results.json

      - name: Store scan results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: sast-results
          path: sast_results.json
